---
services:
  # Database
  db:
    image: mysql:5.7
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_DATABASE: student_info
      MYSQL_PASSWORD: redhat
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    # depends_on:
    #   - db
    image: phpmyadmin:latest
    ports:
      - 9999:80
    environment:
      PMA_HOST: db
    networks:
      - mysql-phpmyadmin

  # nodeapp:
  #   image: node_app:latest
  #   ports:
  #     - 3000:3000
  #   environment:
  #     MYSQL_USERNAME: root
  #     MYSQL_ROOT_PASSWORD: redhat
  #     MYSQL_DATABASE: student_info
  #     MYSQL_HOST: db
  #   networks:
  #     - mysql-phpmyadmin


networks:
  mysql-phpmyadmin:

# volumes:
#   db_data: